# Site
name: "The NeuroBytes Podcast"
title: "The NeuroBytes Podcast"
description: "The NeuroBytes Podcast"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'neurobytes'
mailchimp-list: 'https://neurobytespod.us1.list-manage.com/subscribe/post?u=fd53b3c72e5f8b9843eefd6f5&amp;id=b6f6b60ea7'
include: ["_pages"]
permalink: /:title/
email: admin@neurobytespod.com

# Authors
authors:
  maki:
    name: Maki
    display_name: Maki
    avatar: 'assets/images/avatar_maki_source_getavataaars-com.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: maki@neurobytespod.com
    web: https://hivecrafted.com/
    twitter: https://twitter.com/neurobytespod
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  makisandon:
    name: Maki & Sandon
    display_name: Maki & Sandon
    avatar: 'assets/images/avatar-MakiSandon.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: us@neurobytespod.com
    web: https://hivecrafted.com/
    twitter: https://twitter.com/neurobytespod
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  sandon:
    name: Sandon
    display_name: Sandon
    avatar: 'assets/images/avatar_sandon_source_getavataaars-com.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: sandon@neurobytespod.com
    web: https://hivecrafted.com/
    twitter: https://twitter.com/neurobytespod
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  sandonmaki:
    name: Sandon & Maki
    display_name: Sandon & Maki
    avatar: 'assets/images/avatar-MakiSandon.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: us@neurobytespod.com
    web: https://hivecrafted.com/
    twitter: https://twitter.com/neurobytespod
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, .gitignore]
